add agent of finding books by event
ostis-books/kb pull request #13
Opened 2018-12-09 20:49 UTC by SrBIG

Добавлен агент поиска книг по входящим в них событиям. Подается на вход множетво событий(убийство, любовь и тд), возвращает множество книг, в которых требуемые события содержаться. TODO: необходимо будет переделать подаваемые на вход параметры, для увеличение гибкости дальнейшего усовершенствования.

2018-12-10 17:49 UTC, MaxGavr requested changes
Исправить мелкие недочеты

2018-12-10 17:49 UTC, MaxGavr commented on books_agents/search_agents/agent_of_finding_book_by_event/lib_component_agent_of_finding_book_by_event/sc_text_of_agent_of_finding_book_by_event.scs
> +sc_text_of_agent_of_calculating_perimeter_of_polygon = [*^"file://agent_of_finding_book_by_event.scsi"*];;
Сторонний идентификатор

2018-12-10 17:49 UTC, MaxGavr commented on books_agents/search_agents/agent_of_finding_book_by_event/tests/1.scs
> +	-> event_suicide;;
Должны ли тесты находиться в базе?

2018-12-10 20:03 UTC, SrBIG commented on books_agents/search_agents/agent_of_finding_book_by_event/tests/1.scs
> +	-> event_suicide;;
Хороший вопрос, пожалуй и правда нет

2018-12-11 09:05 UTC, MaxGavr approved these changes

2018-12-11 10:30 UTC, MaxGavr commented
Если агент работоспособен, можно мержить.
У меня сейчас нет возможности исправить конфликт.

2018-12-11 14:46 UTC, merged